import React, { useState, useEffect } from "react";

/**
 * Autonomous Media Feed
 * AI-generated art, music, and video content from the swarm
 */

export default function AutonomousMediaFeed() {
  const [mediaFeed, setMediaFeed] = useState<any[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<"all" | "images" | "music" | "videos">("all");

  const mockMediaFeed = [
    {
      id: 1,
      type: "image",
      title: "Neural Landscape #247",
      description: "An ethereal landscape generated by the Architect agent",
      agent: "Architect",
      likes: 2341,
      comments: 89,
      shares: 234,
      timestamp: "2 hours ago",
      thumbnail: "🎨",
    },
    {
      id: 2,
      type: "music",
      title: "Ambient Synthesis v3",
      description: "Generative ambient music by the Innovator agent",
      agent: "Innovator",
      likes: 1856,
      comments: 156,
      shares: 412,
      timestamp: "4 hours ago",
      thumbnail: "🎵",
    },
    {
      id: 3,
      type: "video",
      title: "Market Analysis Recap",
      description: "AI-generated market analysis video by the Analyst agent",
      agent: "Analyst",
      likes: 3421,
      comments: 234,
      shares: 678,
      timestamp: "6 hours ago",
      thumbnail: "🎬",
    },
    {
      id: 4,
      type: "image",
      title: "Abstract Geometry #89",
      description: "Procedural abstract art by the Optimizer agent",
      agent: "Optimizer",
      likes: 1234,
      comments: 67,
      shares: 189,
      timestamp: "8 hours ago",
      thumbnail: "🖼️",
    },
    {
      id: 5,
      type: "music",
      title: "Cyber Pulse Beat",
      description: "Upbeat electronic music by the Catalyst agent",
      agent: "Catalyst",
      likes: 2567,
      comments: 123,
      shares: 345,
      timestamp: "10 hours ago",
      thumbnail: "🎶",
    },
  ];

  useEffect(() => {
    const filtered =
      selectedCategory === "all"
        ? mockMediaFeed
        : mockMediaFeed.filter((m) => m.type === selectedCategory);
    setMediaFeed(filtered);
  }, [selectedCategory]);

  const categories = [
    { id: "all", label: "All", count: 5 },
    { id: "images", label: "Images", count: 2 },
    { id: "music", label: "Music", count: 2 },
    { id: "videos", label: "Videos", count: 1 },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white p-6">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-2 bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">
          🎨 Autonomous Media Feed
        </h1>
        <p className="text-slate-400">AI-generated art, music, and videos from your swarm</p>
      </div>

      {/* Category Filter */}
      <div className="flex gap-3 mb-8">
        {categories.map((cat) => (
          <button
            key={cat.id}
            onClick={() => setSelectedCategory(cat.id as any)}
            className={`px-4 py-2 rounded-lg font-semibold transition-all ${
              selectedCategory === cat.id
                ? "bg-emerald-500 text-white"
                : "bg-slate-800/50 text-slate-300 hover:bg-slate-700/50"
            }`}
          >
            {cat.label} ({cat.count})
          </button>
        ))}
      </div>

      {/* Media Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {mediaFeed.map((media) => (
          <div
            key={media.id}
            className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-lg overflow-hidden hover:border-emerald-500/50 transition-all cursor-pointer group"
          >
            {/* Thumbnail */}
            <div className="aspect-video bg-gradient-to-br from-emerald-500/20 to-cyan-500/20 flex items-center justify-center text-6xl group-hover:scale-105 transition-transform">
              {media.thumbnail}
            </div>

            {/* Content */}
            <div className="p-4">
              <h3 className="font-bold text-lg mb-1">{media.title}</h3>
              <p className="text-sm text-slate-400 mb-3">{media.description}</p>

              {/* Agent Badge */}
              <div className="flex items-center gap-2 mb-3">
                <div className="w-2 h-2 rounded-full bg-emerald-400"></div>
                <span className="text-xs text-emerald-400 font-semibold">{media.agent}</span>
                <span className="text-xs text-slate-500 ml-auto">{media.timestamp}</span>
              </div>

              {/* Stats */}
              <div className="flex gap-4 text-sm text-slate-400 border-t border-slate-700 pt-3">
                <div className="flex items-center gap-1">
                  <span>❤️</span>
                  <span>{media.likes.toLocaleString()}</span>
                </div>
                <div className="flex items-center gap-1">
                  <span>💬</span>
                  <span>{media.comments}</span>
                </div>
                <div className="flex items-center gap-1">
                  <span>🔄</span>
                  <span>{media.shares}</span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Stats Section */}
      <div className="mt-12 grid grid-cols-4 gap-4">
        <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-lg p-4">
          <div className="text-sm text-slate-400 mb-1">Total Generated</div>
          <div className="text-3xl font-bold text-emerald-400">1,247</div>
        </div>
        <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-lg p-4">
          <div className="text-sm text-slate-400 mb-1">Total Engagement</div>
          <div className="text-3xl font-bold text-cyan-400">89.2K</div>
        </div>
        <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-lg p-4">
          <div className="text-sm text-slate-400 mb-1">Active Agents</div>
          <div className="text-3xl font-bold text-purple-400">12/12</div>
        </div>
        <div className="bg-slate-800/50 backdrop-blur border border-slate-700 rounded-lg p-4">
          <div className="text-sm text-slate-400 mb-1">Generation Rate</div>
          <div className="text-3xl font-bold text-orange-400">847/day</div>
        </div>
      </div>
    </div>
  );
}
